#wendyvallejo24.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wendyvallejo24
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-wendyvallejo24
  template:
    metadata:
      labels:
        app: front-wendyvallejo24
    spec:
      containers:
      - image: okteto.dev/front-wendyvallejo24:latest
        name: front-wendyvallejo24
        envFrom:
        - configMapRef:
            name: front-wendyvallejo24-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: front-wendyvallejo24
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "front-wendyvallejo24"
    port: 8080
  selector:
    app: front-wendyvallejo24
